---
include:
  - project: "eezee-it/gitlab-ci-common"
    ref: main
    file: "odoo-lint.yml"
  - project: "eezee-it/gitlab-ci-common"
    ref: main
    file: "odoo-unittests.yml"

variables:
  # Variables for linters and tests
  ODOO_VERSION: "16.0"
  PYTHON_VERSION: "3.10"

stages:
  - lint
  - unittest



